---
name: Action checks

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  release:
    permissions:
      contents: write
    uses: martoc/workflow-github-actions/.github/workflows/action.yml@v0
    secrets: inherit
